### ISSUE TITLE
After update to 1.5.1 - cannot find module react-scroll

### ISSUE THREAD

**Issue by dacz** [fisshy/react-scroll#205]
Seems like package.json doesn't have proper main:

```
{
  "name": "react-scroll",
  "version": "1.5.1",
  "description": "A scroll component for React.js",
  "main": "modules",
...
```

**Comment by fisshy** [comment]
test now, I was to quick to publish.

**Comment by dacz** [comment]
now ok. thanks. please delete PR #206 (you were very quick to fix it and I was slow to see the fix ;))

**Comment by erinmeyers88** [comment]
A similar issue has be re-introduced with 1.6.0-

package.json in 1.5.5:
"main": "modules",

package.json in 1.6.0
"main": "build/npm/modules"
