### ISSUE TITLE
Uncaught TypeError: cancelEvents.subscribe is not a function

### ISSUE THREAD

**Issue by michelarteta** [fisshy/react-scroll#296]
Hello, after upgrading from 1.5.4 to 1.7.4 I got this error. Any ideas? Thank you. 
```
Uncaught TypeError: cancelEvents.subscribe is not a function
    at Object.defineProperty.value (animate-scroll.js:58)
    at __webpack_require__ (bootstrap 990563e4537eb3780ba3:19)
    at Object.<anonymous> (scroller.js:13)
    at __webpack_require__ (bootstrap 990563e4537eb3780ba3:19)
    at Object.defineProperty.value (Helpers.js:18)
    at __webpack_require__ (bootstrap 990563e4537eb3780ba3:19)
    at Object.defineProperty.value (Link.js:12)
    at __webpack_require__ (bootstrap 990563e4537eb3780ba3:19)
    at Object.defineProperty.value (index.js:3)
    at __webpack_require__ (bootstrap 990563e4537eb3780ba3:19)
```

**Comment by fisshy** [comment]
Are you using babel-loader? 

loaders: [
      {
        test: /\.js$/, loader: 'babel-loader',
        query: {
          presets: ['es2015', 'react'],
          plugins: ["transform-class-properties"]
        }
      }
    ]
